name: Selenium Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout code

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Setup ChromeDriver
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: latest

    - name: Print Working Directory
      run: pwd

    - name: Print Working Directory
      run: echo $GITHUB_WORKSPACE

    - name: Run Selenium Test
      env:
        PYTHONPATH: $GITHUB_WORKSPACE/Infra
      run: python $GITHUB_WORKSPACE/Test/test_get.py
